variables:
  DOCKER_REPOSITORY: mendersoftware/mender-convert-integration-scripts
  S3_BUCKET_NAME: mender
  DOCKER_VERSION:
    value: "29.1"
    description: "Version of docker to use in pipelines"
  DOCKER_HOST:
    value: 'tcp://docker:2376'
    description: "Required to run dind inside k8s runners with TLS"
  DOCKER_TLS_CERTDIR:
    value: '/certs'
    description: "The cert dir inside the gitlab runner. Don't change this."
  DOCKER_TLS_VERIFY:
    value: "1"
    description: "Enable TLS verification for docker in dind"
  DOCKER_CERT_PATH:
    value: "$DOCKER_TLS_CERTDIR/client"
    description: "Used for docker entrypoints. See https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4125"

include:
  - component: gitlab.com/Northern.tech/Mender/mendertesting/commit-lint@master
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

default:
  image: debian:trixie

stages:
  - test
  - build
  - publish

build:uboot:
  stage: build
  image: docker
  services:
    - name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/docker:${DOCKER_VERSION}-dind
      alias: docker
  script:
    - IMAGE_NAME=$DOCKER_REPOSITORY:pr ./docker-create-integration-binaries
  artifacts:
    expire_in: 2w
    paths:
      - output/*

publish:s3:
  stage: publish
  dependencies:
    - build:uboot
  before_script:
    - apt update && apt install -yyq awscli
  script:
    - ./prepare-output-folder-for-upload
    - aws s3 cp --recursive --acl public-read output/upload/ s3://$S3_BUCKET_NAME/mender-convert/
  only:
    - /^(master|[0-9]+\.[0-9]+\.x)$/
