variables:
  DOCKER_REPOSITORY: mendersoftware/mender-convert-integration-scripts
  S3_BUCKET_NAME: mender

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

default:
  image: debian:trixie

stages:
  - test
  - build
  - publish

build:uboot:
  stage: build
  image: docker
  services:
    - docker:20.10.21-dind
  script:
    - IMAGE_NAME=$DOCKER_REPOSITORY:pr ./docker-create-integration-binaries
  artifacts:
    expire_in: 2w
    paths:
      - output/*

publish:s3:
  stage: publish
  dependencies:
    - build:uboot
  before_script:
    - apt update && apt install -yyq awscli
  script:
    - ./prepare-output-folder-for-upload
    - aws s3 cp --recursive --acl public-read output/upload/ s3://$S3_BUCKET_NAME/mender-convert/
  only:
    - /^(master|[0-9]+\.[0-9]+\.x)$/
